import Pkg; Pkg.add("LaTeXStrings")
println("Installation Done:\tLaTeXStrings")
import Pkg; Pkg.add("Markdown")
println("Installation Done:\tMarkdown")
import Pkg; Pkg.add("Printf")
println("Installation Done:\tPrintf")
import Pkg; Pkg.add("LinearAlgebra")
println("Installation Done:\tLinearAlgebra")
import Pkg; Pkg.add("LaTeXStrings")
println("Installation Done:\tLaTeXStrings")
import Pkg; Pkg.add("PrettyTables")
println("Installation Done:\tPrettyTables")
import Pkg; Pkg.add("NLsolve")
println("Installation Done:\tNLsolve")
import Pkg; Pkg.add("SymPy")
println("Installation Done:\tSymPy")
import Pkg; Pkg.add("Roots")
println("Installation Done:\tRoots")
import Pkg; Pkg.add("PyCall")
println("Installation Done:\tPyCall")