precompile(Tuple{Base.var"#@r_str", LineNumberNode, Module, Any, Vararg{Any}})
precompile(Tuple{ArrayInterface.var"#100#104"})
precompile(Tuple{ArrayInterface.var"#101#105"})
precompile(Tuple{ArrayInterface.var"#102#106"})
precompile(Tuple{Base.var"#@__FILE__", LineNumberNode, Module})
precompile(Tuple{typeof(Demo.julia_main)})
precompile(Tuple{Markdown.var"#@md_str", LineNumberNode, Module, Any, Vararg{Any}})
precompile(Tuple{Base.Cartesian.var"#@ncall", LineNumberNode, Module, Int64, Any, Vararg{Any}})
precompile(Tuple{typeof(Demo.show_result), Function, Array{Int64, 1}, Array{Float64, 1}, Array{Int64, 1}, Array{Int64, 1}, String, LaTeXStrings.LaTeXString})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), Base.Broadcast.DefaultArrayStyle{1}, Function, Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Demo.f), Tuple{Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Demo.f), Tuple{Array{Float64, 1}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.lagrange), Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Array{Float64, 1}, Array{Float64, 1}})
precompile(Tuple{Printf.var"#@sprintf", LineNumberNode, Module, Any, Vararg{Any}})
precompile(Tuple{Formatting.var"#11#12", Float64})
precompile(Tuple{typeof(Demo.show_result), Function, Array{Int64, 1}, Array{Float64, 1}, Array{Int64, 1}, Array{Any, 1}, String, LaTeXStrings.LaTeXString})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Base.StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.show_result), Function, Nothing, Array{Int64, 1}, Array{Int64, 1}, Array{Int64, 1}, Array{Any, 1}, String, LaTeXStrings.LaTeXString, LaTeXStrings.LaTeXString})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Demo.f), Tuple{Array{Int64, 1}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Int64, 1}}}})
precompile(Tuple{typeof(Demo.lagrange), Array{Int64, 1}, Array{Float64, 1}, Array{Int64, 1}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Int64, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Int64, 1}}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Int64, 1}}}})
precompile(Tuple{Printf.var"#@printf", LineNumberNode, Module, Any, Vararg{Any}})
precompile(Tuple{typeof(Demo.romberg), typeof(Demo.f), Tuple{Int64, Int64}, Int64, Float64})
precompile(Tuple{typeof(Printf.format), Base.TTY, Printf.Format{Base.CodeUnits{UInt8, String}, Tuple{Printf.Spec{Base.Val{Char(0x66000000)}}}}, Float64})
precompile(Tuple{typeof(Demo.romberg), typeof(Demo.f), Tuple{Int64, Int64}, Int64, Float64})
precompile(Tuple{typeof(Demo.romberg), typeof(Demo.f), Tuple{Int64, Int64}, Int64, Float64})
precompile(Tuple{typeof(Demo.romberg), typeof(Demo.f), Tuple{Int64, Int64}, Int64, Float64})
precompile(Tuple{typeof(Demo.show_result), Function, Function, Function, Tuple{Float64, Float64}, Float64, Array{Int64, 1}, Bool, Bool, LaTeXStrings.LaTeXString, LaTeXStrings.LaTeXString})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Axes, F, Args} where Args<:Tuple where F where Axes}, typeof(Demo.f3), Tuple{Array{Float64, 1}}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{Formatting.var"#13#14", Float64})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.rungekutta), typeof(Demo.f2), Tuple{Float64, Float64}, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f3), Tuple{Array{Float64, 1}}}})
precompile(Tuple{Type{Printf.Spec{Base.Val{Char(0x64000000)}}}, Bool, Bool, Bool, Bool, Bool, Int64, Int64})
precompile(Tuple{Type{Printf.Format{S, T} where T where S}, Base.CodeUnits{UInt8, String}, Array{Base.UnitRange{Int64}, 1}, Tuple{Printf.Spec{Base.Val{Char(0x64000000)}}}})
precompile(Tuple{SymPy.var"#@syms", LineNumberNode, Module, Vararg{Any}})
precompile(Tuple{typeof(Demo.show_result), Function, Float64, Float64, Float64, Int64, LaTeXStrings.LaTeXString})
precompile(Tuple{typeof(Demo.get_func_diff), typeof(Demo.f)})
precompile(Tuple{typeof(Demo.f), SymPy.Sym})
precompile(Tuple{typeof(Demo.redefine_func), Function, SymPy.var"#107#108"{SymPy.var"###291"}})
precompile(Tuple{typeof(Demo.collect_data), Function, Function, Function, Function, Float64, Float64, Float64, Int64, Int64})
precompile(Tuple{typeof(Demo.f), Float64})
precompile(Tuple{typeof(Core.Compiler.return_type), Any, Any, UInt64})
precompile(Tuple{NLSolversBase.var"#fj!#7"{Demo.var"#f!#1"{typeof(Demo.f)}, Demo.var"#j!#2"{SymPy.var"#107#108"{SymPy.var"###291"}}}, Array{Float64, 1}, Array{Float64, 2}, Array{Float64, 1}})
precompile(Tuple{SymPy.var"###291", Float64})
precompile(Tuple{typeof(Demo.newton), typeof(Demo.f), SymPy.var"#107#108"{SymPy.var"###291"}, Float64, Float64, Int64, Float64, Float64})
precompile(Tuple{typeof(Base.vect), Float64, Vararg{Any}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.f), SymPy.Sym})
precompile(Tuple{typeof(Demo.redefine_func), Function, SymPy.var"#107#108"{SymPy.var"###292"}})
precompile(Tuple{typeof(Demo.f), Float64})
precompile(Tuple{NLSolversBase.var"#fj!#7"{Demo.var"#f!#1"{typeof(Demo.f)}, Demo.var"#j!#2"{SymPy.var"#107#108"{SymPy.var"###292"}}}, Array{Float64, 1}, Array{Float64, 2}, Array{Float64, 1}})
precompile(Tuple{SymPy.var"###292", Float64})
precompile(Tuple{typeof(Demo.newton), typeof(Demo.f), SymPy.var"#107#108"{SymPy.var"###292"}, Float64, Float64, Int64, Float64, Float64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.f), SymPy.Sym})
precompile(Tuple{typeof(Demo.redefine_func), Function, SymPy.var"#107#108"{SymPy.var"###293"}})
precompile(Tuple{typeof(Demo.f), Float64})
precompile(Tuple{NLSolversBase.var"#fj!#7"{Demo.var"#f!#1"{typeof(Demo.f)}, Demo.var"#j!#2"{SymPy.var"#107#108"{SymPy.var"###293"}}}, Array{Float64, 1}, Array{Float64, 2}, Array{Float64, 1}})
precompile(Tuple{SymPy.var"###293", Float64})
precompile(Tuple{typeof(Demo.newton), typeof(Demo.f), SymPy.var"#107#108"{SymPy.var"###293"}, Float64, Float64, Int64, Float64, Float64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.show_result), Function, Float64, Int64, Float64, Float64, Int64, LaTeXStrings.LaTeXString})
precompile(Tuple{typeof(Demo.f), SymPy.Sym})
precompile(Tuple{typeof(Demo.redefine_func), Function, SymPy.var"#107#108"{SymPy.var"###294"}})
precompile(Tuple{typeof(Demo.f), Float64})
precompile(Tuple{NLSolversBase.var"#fj!#7"{Demo.var"#f!#1"{typeof(Demo.f)}, Demo.var"#j!#2"{SymPy.var"#107#108"{SymPy.var"###294"}}}, Array{Float64, 1}, Array{Float64, 2}, Array{Float64, 1}})
precompile(Tuple{SymPy.var"###294", Float64})
precompile(Tuple{typeof(Demo.newton), typeof(Demo.f), SymPy.var"#107#108"{SymPy.var"###294"}, Float64, Float64, Int64, Float64, Float64})
precompile(Tuple{typeof(Demo.newton), typeof(Demo.f), SymPy.var"#107#108"{SymPy.var"###294"}, Float64, Float64, Int64, Float64, Int64})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Demo.f), Tuple{Array{Float64, 1}}}})
precompile(Tuple{typeof(Demo.show_result), Array{Float64, 2}, Array{Float64, 1}})
precompile(Tuple{Formatting.var"#15#16", Float64})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}, Function})
precompile(Tuple{typeof(Base.hvcat), Tuple{Int64, Int64, Int64, Int64}, Float64, Vararg{Number}})
precompile(Tuple{typeof(Base.hvcat), Tuple{Int64, Int64, Int64, Int64}, Int64, Vararg{Number}})
precompile(Tuple{typeof(Demo.show_result), Array{Int64, 2}, Array{Int64, 1}})
